### ISSUE TITLE
Documenting the private groups workflow

### ISSUE THREAD

**Issue by klemay** [hypothesis/support#18]
These are presented in the order in which they need to be written / added to WP to avoid going back and linking to new articles as they're written:
- [x] Activating Hypothesis on a web page: https://github.com/hypothesis/support/issues/16
- [x] Annotating with groups: https://github.com/hypothesis/support/issues/17
- [x] How to join a private group: https://github.com/hypothesis/support/issues/15
- [x] Invite people to join: https://github.com/hypothesis/support/issues/14
- [x] Creating a private group: https://github.com/hypothesis/support/issues/13
- [x] Update the "Annotating with groups" page
